//Nome: Luís Henrique de Jesus Lima - RA: 2313642

package com.mycompany.empdev;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RelGerClie extends javax.swing.JFrame {

        private Cliente cliente = new Cliente();
        private static RelGerClie unicoRGF;
        private static ClieGer gc;
  
    private RelGerClie() {
        initComponents();
    }
    
    public static RelGerClie getRelGerClie(ClieGer gc1){
        gc = gc1;
        if(unicoRGF == null){
            unicoRGF = new RelGerClie();
        }
        return unicoRGF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabClie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        tabClie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "NOME", "IDADE", "ESTADO", "CIDADE", "RUA", "NÚMERO", "D. ÚLTIMA COMPRA", "SERVIÇO"
            }
        ));
        tabClie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabClie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClieMouseClicked
        selectTabClie();
    }//GEN-LAST:event_tabClieMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       listaTab();
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
      public void selectTabClie(){
        String valLinTab = "";
        int posLin = tabClie.getSelectedRow();
          
        
        for(int coluna = 0;coluna < tabClie.getColumnCount(); coluna++ ){
            valLinTab += tabClie.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna+1 < tabClie.getRowCount()){
               valLinTab += " - ";
            }
            
        }
        JOptionPane.showMessageDialog(
                null,
                "Valor escolhido: "+valLinTab,
                "Seleção na tabela",
                1
        );
    }
    public void listaTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabClie.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Cliente cliente : gc.getBdClie() ){
            modelo.insertRow(
                posLin, 
                new Object[]{
                    cliente.getCpf(), 
                    cliente.getName(), 
                    cliente.getAge(), 
                    cliente.getAddress().getReg().getEstado(), 
                    cliente.getAddress().getReg().getCidade(),
                    cliente.getAddress().getStreet(), 
                    cliente.getAddress().getNumber(),
                    cliente.getDataUltimaCompra(),
                    cliente.getServico()
                }
            );
            posLin++;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelGerClie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelGerClie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelGerClie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelGerClie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelGerClie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabClie;
    // End of variables declaration//GEN-END:variables
}
